imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:     ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    default_locale: %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine MongoDB
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_database: tripshaper_%kernel.environment%
    document_managers:
        default:
            auto_mapping: true
    auto_generate_hydrator_classes: true 
    auto_generate_proxy_classes:  true
            
# Swiftmailer Configuration
# swiftmailer:
#    transport: %mailer_transport%
#    host:      %mailer_host%
#    username:  %mailer_user%
#    password:  %mailer_password%

# JMS
jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false
     expressions: true
   
# Elastica
foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        ileyeu:
            client: default
            types:
#                place:
#                    mappings:
#                        title:
#                    persistence:
#                        driver: mongodb
#                        model: TripShaper\StoreBundle\Document\Place
#                        provider:
#                        listener:
#                        finder:
                tag:
                    mappings:
                        term:
                    persistence:
                        driver: mongodb
                        model: TripShaper\StoreBundle\Document\Tag
                        provider:
                        listener:
                        finder:
  
# Menu
knp_menu:
    twig: true
    
# Admin Generator
admingenerator_generator:
    base_admin_template: TripShaperAdminBundle::base_admin_assetic_less.html.twig
    knp_menu_class: TripShaper\AdminBundle\Menu\AdminMenu
    use_doctrine_orm: false
    use_doctrine_odm: true
    use_propel: false
admingenerator_user:
    login_template: AdmingeneratorGeneratorBundle::base_login_assetic_less.html.twig

# FOS User
fos_user:
    service:
        mailer: fos_user.mailer.noop
    user_class:  TripShaper\AdminBundle\Document\User 
    db_driver: mongodb
    firewall_name: main

# Twig            
twig:
    form:
        resources:
            - 'TripShaperAdminBundle:Form:fields.html.twig'