generator: admingenerator.generator.doctrine_odm
params:
  model: TripShaper\StoreBundle\Document\Place
  namespace_prefix: TripShaper
  bundle_name: AdminBundle
  fields:
    title:
        getter: DefaultTitle
    shortDescription:
        formType: textarea
        label: Short description
    localDescription:   
        formType: textarea
        label: Local description
    marketingDescription: 
        formType: textarea  
        label: Marketing description

builders:
  list:
    params:
      title: Places
      display: [ title ]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [ ]
  new:
    params:
      title: New Place
      display: 
        "NONE": []
        "Titles": []
        "Descriptions": [ shortDescription, localDescription, marketingDescription  ]
        "Geolocation": [ ]
        "Tags": []
      actions:
        list: ~
  edit:
    params:
      title: "{{ Place.id }}"
      display: 
        "NONE": []
        "Titles": []
        "Descriptions": [ shortDescription, localDescription, marketingDescription  ]
        "Geolocation": []
        "Tags": []
      actions:
        list: ~
  delete: ~
