generator: admingenerator.generator.doctrine_odm
params:
  model: TripShaper\StoreBundle\Document\Trip
  namespace_prefix: TripShaper
  bundle_name: AdminBundle
  fields:
    title:
        getter: DefaultTitle

builders:
  list:
    params:
      title: Trips
      display:
        display: [ title ]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New Trip
      display: ~
      actions:
        list: ~
  edit:
    params:
      title: "{{ Trip.id }}"
      display:
        "Titles": []
      actions:
        list: ~
  delete: ~
